name: build-movies-admin-panel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run lint
      - run: npm run build
        env:
          API_HOST: "http://84.201.189.140:8088"
          IMAGES_HOST: "http://84.201.189.140:8088"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: webpack-app
          path: ./build

  deployS3:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: webpack-app

      - name: Deploy to Yandex Cloud Object Storage
        uses: paulvstrashnov/yandex-s3-upload-action@main
        with:
          accessKeyId: ${{ secrets.AWS_KEY_ID }}
          secretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          bucket: ${{ secrets.AWS_BUCKET }}
          localPath: './'
          remotePath: "admin/"

      - name: Change current version
        uses: paulvstrashnov/yandex-s3-upload-action@main
        with:
          accessKeyId: ${{ secrets.AWS_KEY_ID }}
          secretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          bucket: ${{ secrets.AWS_BUCKET }}
          localPath: './version.txt'
          remotePath: "admin"