name: build-movies-admin-panel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run lint
      - run: npm run build
        env:
          API_HOST: "http://84.201.189.140:8088"
          IMAGES_HOST: "http://84.201.189.140:8088"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: webpack-app
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: webpack-app

      - name: 'Deploy to web server'
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        id: deploy-to-server
        with:
          server: 'w96505me.beget.tech'
          protocol: 'ftp'
          username: 'w96505me_deploy'
          password: ${{ secrets.BEGET_SERVER_PUBLISH_PASS }}
          local-dir: './'